### ISSUE TITLE
V3 norminette on Visualizer

### ISSUE THREAD

**Issue by benmaia** [alexandregv/norminette-vim#2]
Hey, I installed the v3 norminette, running the commands here [](https://github.com/42School/norminette), and after that installed the plugins by vim-plug as you have in you're tutorial, installed and put the config equal as yours in .vimrc, but changed the `let g:syntastic_c_norminette_exec = '~/.norminette/norminette.rb'` to `let g:syntastic_c_norminette_exec = 'norminette'`, and when I open the .c file doesn't show anything, also if I run `:Errors` doesn't do anything, and if I run `:Norminette` it says that doesn't existe the file or directory `/home/user/.norminette/norminette.rb`, what is normal because I didn't install the V2.
![Screenshot from 2022-05-07 13-27-48](https://user-images.githubusercontent.com/86362288/167254438-05b23ac9-c8f5-4dee-ba78-db053980e597.png)

**Comment by benmaia** [comment]
Fixed the `:Norminette` giving me that error, you have to go to `/home/$(whoami)/.vim/plugged/norminette-vim/complier/norminette.vim` and change the line `if !exists(g:norminette_exec" | let g:norminette_exec="~/.norminette/norminette.rb" || endif` to `if !exists(g:norminette_exec" | let g:norminette_exec="norminette" || endif`, but still without the "visualizer". 
![Screenshot from 2022-05-07 14-06-59](https://user-images.githubusercontent.com/86362288/167255880-179b3eea-9127-4a79-92c2-40e4a2e7f722.png)

But still, if I have norm errors the vim won't show them to me, like a visualizer.

![Screenshot from 2022-05-07 14-10-23](https://user-images.githubusercontent.com/86362288/167255883-7720b664-f060-4667-9a5b-516c8d447e3d.png)
.

**Comment by alexandregv** [comment]
Hi,  
I think the problem comes from your installation. I saw your post on slack, it is not normal that you still see some `norminette.rb` if you use the v3, since `norminette.rb` is the v2.

Please make sure to uninstall norminette v2, remove any alias in your .zshrc/.bashrc/etc, and any symlink or whatever.  
Then check with `whereis norminette` and `which norminette` and `type -a norminette` to make sure the right norminette is installed and used.  
Then set the line `let g:syntastic_c_norminette_exec = 'norminette'` in the config, only if `which norminette` points to the good `norminette` executable. Otherwise, fix your PATH to include python's bin directory, or set the config line to the absolute path of the executable.

If you still have the problem, please post the output of those commands:
```bash
set -x
whereis norminette
which norminette
type -a norminette
norminette --version
grep syntastic_c_norminette_exec ~/.vimrc ~/.config/nvim/init.vim
set +x
```

**Comment by alexandregv** [comment]
I'm not sure to understand your second message.  
1. The `:Norminette` command will never show the indicators on the left, it's a basic feature in case you didn't installed the full plugin etc (check [this section of the README](https://github.com/alexandregv/norminette-vim#dont-want-to-bother-with-this-syntasticplugins-stuff-check-this)).
2. On your last screenshot, isn't it working?

**Comment by benmaia** [comment]
> Hi, I think the problem comes from your installation. I saw your post on slack, it is not normal that you still see some `norminette.rb` if you use the v3, since `norminette.rb` is the v2.
> 
> Please make sure to uninstall norminette v2, remove any alias in your .zshrc/.bashrc/etc, and any symlink or whatever. Then check with `whereis norminette` and `which norminette` and `type -a norminette` to make sure the right norminette is installed and used. Then set the line `let g:syntastic_c_norminette_exec = 'norminette'` in the config, only if `which norminette` points to the good `norminette` executable. Otherwise, fix your PATH to include python's bin directory, or set the config line to the absolute path of the executable.
> 
> If you still have the problem, please post the output of those commands:
> 
> ```shell
> set -x
> whereis norminette
> which norminette
> type -a norminette
> norminette --version
> grep syntastic_c_norminette_exec ~/.vimrc ~/.config/nvim/init.vim
> set +x
> ```

**Comment by benmaia** [comment]
I never installed V2 thats the thing, I just installed the V3, and in the 1st print it's the solution i've found, i've had to change the norminette.vim in the compiler folder, because in line 18 it was written norminette.rb, but yea, now it's working! Maybe it's something you've forgot to put on READ.ME idk, had to look in the files ahahah

**Comment by alexandregv** [comment]
You are not supposed to edit the code of the plugin, only the config (as described in the README). So if you had to edit the code that is not normal 🤔  
My guess it that you didn't set `g:norminette_exec`, I will clarify it in the README, and make v3 the default since it's now the default in every campuses.

**Comment by alexandregv** [comment]
@benmaia Could you please confirm that the latest version (with 2 new commits) without any local edit from you is working fine on your setup? Thanks

**Comment by benmaia** [comment]
I've did, i've change the g:norminette_exec and it didn't worked, I had to change the code itself, ill try

**Comment by benmaia** [comment]
I think it's working now, yea, you had one of the !exists comments in the original file, maybe it's because of that

**Comment by alexandregv** [comment]
The commented line made `g:norminette_exec` fallback to `g:syntastic_c_norminette_exec` if possible. I disabled it a time ago for a reason that I can't remember. I now changed the default value to `norminette` (i.e norminette v3 instead of v2) and re-enabled the fallback.  
Glad to hear it's working! Thanks.
